root: true
extends:
- eslint:recommended
- plugin:react/recommended
- plugin:react-hooks/recommended
- plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  project:
  - ./tsconfig.json
plugins:
- react
- '@typescript-eslint'
- require-prevent-default
rules: {require-prevent-default/require-prevent-default: error, react/react-in-jsx-scope: off}
ignorePatterns: [dist]
