#!/bin/bash
set -eux -o pipefail

SCRIPT_FOLDER=$(dirname $(realpath $0))

VERSION=7.26.3
PNPM=${SCRIPT_FOLDER}/.downloads/pnpm-${VERSION}

if [ ! -f $PNPM ]; then
    mkdir -p ${SCRIPT_FOLDER}/.downloads
    wget https://github.com/pnpm/pnpm/releases/download/v${VERSION}/pnpm-linuxstatic-x64 --output-document=${PNPM}
    chmod +x $PNPM
fi

$PNPM $*
