version: '3'
services:
  selenium:
    image: selenium/standalone-chrome:4.8.0-20230202
    shm_size: 2gb
  ui-tests:
    build: tests
    volumes:
    - ./tests:/work:cached
    environment:
    - SELENIUM_URL=http://selenium:4444/wd/hub
    links:
    - nginx
    - backend
    - frontend
    command: bash -c "wait-for-it -t 0 nginx:8000 -- wait-for-it -t 0 frontend:9000 -- wait-for-it -t 0 backend:5000 -- wait-for-it -t 0 selenium:4444 -- pytest -vvv -s ."
