on:
  push:
    branches:
    - main
  pull_request:

name: Continuous integration

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1.0.7
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: clippy, rustfmt
    - uses: Swatinem/rust-cache@v2
      with:
        cache-directories: backend
    - name: Check formatting
      run: cd backend && cargo fmt -- --check
    - name: Clippy
      env:
        RUSTFLAGS: -Dwarnings
      run: cd backend && cargo clippy
    - name: Build
      run: cd backend && cargo build
    - name: Test
      run: cd backend && cargo test

  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install pnpm script
      run: |
        mkdir /home/runner/.local/bin
        cp frontend/pnpm ~/.local/bin
    - uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: pnpm
        cache-dependency-path: frontend/pnpm-lock.yaml
    - name: Install packages
      run: cd frontend && pnpm install
    - name: Compile
      run: cd frontend && pnpm run build
    - name: Check types
      run: cd frontend && pnpm run check-types

  integration-tests:
    name: Docker tests
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
    - uses: actions/checkout@v2
    - name: Run docker-compose
      env:
        COMPOSE_FILE: docker-compose.yml:docker-compose.tests.yml
      run: |
        docker-compose up --build --exit-code-from ui-tests
