on:
  push:
    branches:
    - main
  pull_request:

name: Continuous integration

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions-rs/toolchain@v1.0.7
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: clippy, rustfmt
    - uses: Swatinem/rust-cache@v2
      with:
        cache-directories: backend
    - name: Check formatting
      run: cd backend && cargo fmt -- --check
      # - name: Clippy
      #   uses: actions-rs/cargo@v1.0.3
      #   env:
      #     RUSTFLAGS: -Dwarnings
      #   with:
      #     command: clippy
    - name: Build
      run: cd backend && cargo build
    - name: Test
      run: cd backend && cargo test

  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: npm
        cache-dependency-path: frontend/package-lock.json
    - name: Prepare java
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '8'
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@9.5
      with:
        cli: 1.10.1.693
    - name: Cache clojure dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: cljdeps-${{ hashFiles('frontend/deps.edn') }}
        restore-keys: cljdeps-
    - name: Install packages
      run: cd frontend && npm install
    - name: Compile
      run: cd frontend && npm run compile
